mount_directory:                 "/"
root_directory:                  "/u01"
stage_dir:                       "/u01/stage"
scripts_directory:               "{{ root_directory }}/app/scripts"
oracle_base:                     /u01/app/oracle
oracle_home:                     /u01/app/oracle/product/19.3.0/db100
oracle_inventory:                /u01/app/oraInventory 
oracle_user:                     root
root_user:                       root
oradbsoft_rsp:                   "19cEE_SoftOnly"    
preinstall_pkg:                  "oracle-database-preinstall-19c-1.0-1.el7.src.rpm"
oracle19c_url:                   "https://www.oracle.com/technetwork/database/enterprise-edition/downloads/oracle19c-linux-5462157.html"
