---
# tasks file for playrole

 - name: update yum
   yum:
     name: "*"
     state: latest

 - name: install repository rpm for PostgreSQL
   yum:
     name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
     state: latest

 - name: "Find out if PostgreSQL is initialized"
   ansible.builtin.stat:
     path: "/var/lib/pgsql/13/data/pg_hba.conf"
   register: postgres_data
 - debug:
     var: postgres_data

 - name: install PostgreSQL version {{version}}
   yum:
     name: "{{ item }}"
     state: latest
   with_items:
     - postgresql{{version}}-server

 - name: Initialize the database create data cluster if not exist
   command: /usr/pgsql-{{version}}/bin/postgresql-{{version}}-setup initdb
   when: not postgres_data.stat.exists

 - name: Enable automatic start
   service:
     name: postgresql-{{version}}
     state: started
     enabled: yes

   notify:
     - Restart psql

 - name: install psycopg2
   yum:
     name: python-psycopg2

 - name: Run query to List all databases
   become: yes
   become_user: postgres
   postgresql_query:
     login_user: postgres
     port: 5432
     db: postgres
     query: SELECT datname from pg_database
   register: info
   
 - name: Print List of databases
   debug:
     msg: "{{ info }}"
